{% set name = "psycopg-pool" %}
{% set version = "3.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: fa115eb2860bd88fce1717d75611f41490dec6135efb619611142b24da3f6db5

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=80.3.1
    - pip
  run:
    - python >={{ python_min }}
    - typing_extensions >=4.6

test:
  imports:
    - psycopg_pool
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip
    - psycopg >=3.0

about:
  home: https://psycopg.org/psycopg3/
  summary: Connection Pool for Psycopg
  license: LGPL-3.0-or-later
  license_file: LICENSE.txt
  doc_url: https://www.psycopg.org/psycopg3/docs/advanced/pool.html
  dev_url: https://github.com/psycopg/psycopg/

extra:
  recipe-maintainers:
    - xylar
